### PR TITLE
Code Rafactorization and add public method

### PR DESCRIPTION
**Pull request by bpavie**
The goal was to refactorized the code so we could have public method that could be called from Scripts in Jython/Beanshell/... and also from other Fiji/ImageJ plugins.

Each transformation matrix is described in a class `Matrix_xxx` extending the abstract class `MatrixTransformation` that contain all the methods, including the public one. I added some example on the documentation of the class `MatrixTransformation`  to explain how to use from the public method.

I also added a `public static void main` method in the Main class `Colour_Deconvolution` to test it and moved all classes into a package `colourdeconvolution`

I didn't change anything from the plugin interface so the refactorized plugin is retro-compatible with the previous version from the ImageJ Macro language.

### CODE REVIEW

**Comment by imagejan** [comment]
@bpavie The way you made the commits makes it very hard to review what was changed, since you mixed moving the files with the actual changes. Can you try to first create a commit moving the files into a new package, and then commit your code changes in a second commit?

**Comment by landinig** [comment]
I wonder if it would be better than creating extra matrix files for the built-in vectors, to have a single companion text file with the vector values, that is read at run time where one could add additional vectors as desired without having to edit and compile the source.
While recompiling the original plugin to add or modify a stain vector is easy in IJ1, it is not that straightforward for Fiji, and IJ2, I think.

**Comment by bpavie** [comment]
imagejan > Do you want me to delete it refork then redo the pull request? Or is there a better way?
landinig > Do you have any plugin example to point so I could implement that in another branch? I am not sure where could be the best place to store the text file.

**Comment by imagejan** [comment]
> Do you want me to delete it refork then redo the pull request? Or is there a better way?

@bpavie The recommended way is to rebase your own branch and then force-push to the branch that is the source of this PR. This assures that the pull request will automatically reflect all the changes.

For details, see:
http://imagej.net/How_to_contribute_to_an_existing_plugin_or_library#Modifying_your_commits

**Comment by bpavie** [comment]
I am not sure I understand how to proceed. It looks easier to me to redo a fork and then do a pull request..

**Comment by landinig** [comment]
Hi bpavie. I do not have an example to show how to load a txt file with the vectors, sorry.
Presumably it would be one staining method per line, with:
name, r2, g1, b1, r2, g2, b2, r3, g3, b3
either comma or tab delimited file?
That could sit in the plugins folder which exists in every install.

I am not clear the new format you are proposing with so many java files (one per stain) is the way I would like this to go. For instance, adding a new colour vector is currently straightforward in plain ImageJ, all in the same code and can be done simply from the editor. 
How easy would it be with the proposed changes? 

Fiji/IJ2 do not ship the sources, so how would anybody add new vectors?
That is crucial, the built-in vectors are there only as examples, I would expect everybody who is serious about their analyses to determine their own values according to the techniques and protocols they use so it would be of benefit to have a mechanism that makes adding or modifying stains an easy task for any everybody, regardless of whether they are using ImageJ, ImageJ2 or Fiji.
Maybe we can discuss this a bit before carrying on further.

**Comment by imagejan** [comment]
> Fiji/IJ2 do not ship the sources, so how would anybody add new vectors?

@landinig You could make it even more user friendly and allow to save the values entered in the "User values" option in some IJ.Prefs, adding an arbitrary amount of user-defined vecors without the need of hacking the source.

On the other hand, if you prefer to have an external txt file, make sure to put it into the `./lib/` folder, not in `./plugins/`, so that it gets picked up by the updater. See http://imagej.net/Uploading_plugins#File_organization for details.

**Comment by bpavie** [comment]
@Jan Eglinger : I resubmitted a pull request after having done the commit
in multiple steps, since I wasn't sure how to rebase.

@landinig: The plugin can already take custom values from the user, I kept
this possibility (including the one to get the value from selecting some
area from the GUI).  I also add this possibility from the public method
(see comment in MatrixTransformation.java
https://github.com/bpavie/Colour_Deconvolution/blob/refactor/src/main/java/colourdeconvolution/MatrixTransformation.java
)

2015-11-19 12:59 GMT+01:00 Jan Eglinger notifications@github.com:

**Comment by landinig** [comment]
Thanks for the ideas. 
This has to work for all Fiji/IJ2 and plain ImageJ. There is no .lib in ImageJ (or in the Fiji install I have) or am I missing something?

**Comment by bpavie** [comment]
There is no lib directory in Fiji/IJ2.
I could put it in plugin directory. In this case, where do I commit the
code in the plugin?

Is a text file like that would be OK:

#Stain Name             ,MODx[0]    ,MODy[0]    ,MODz[0]    ,MODx[1]
,MODy[1]   ,MODz[1]   ,MODx[2]   ,MODy[2]   ,MODz[2]
H&E
,0.644211000,0.716556000,0.266844000,0.09278900,0.95411100,0.28311100,0.00000000,0.00000000,0.0000000
H&E 2
,0.490157340,0.768970850,0.410401730,0.04615336,0.84206840,0.53739250,0.00000000,0.00000000,0.0000000
...

2015-11-19 13:09 GMT+01:00 landinig notifications@github.com:

**Comment by imagejan** [comment]
> There is no lib directory in Fiji/IJ2. I could put it in plugin directory.

@bpavie @landinig The point is that if you put a text file into `./plugins/` the ImageJ updater will not pick it up for uploading it to the update site. You can simply create a `./lib/` directory, put your file there, and it should work for the updater. But I don't know about plain IJ1.

Maybe @ctrueden or @hinerm can comment on the best way to do this?

**Comment by bpavie** [comment]
@Jan Eglinger : I resubmitted a pull request after having done the commit
in multiple steps, since I wasn't sure how to rebase.

@landinig: The plugin could already take custom values from the user, I
kept this possibility (including the one to get the value from selecting
some area from the GUI).  I also add this possibility from the public
method (see comment in MatrixTransformation.java
https://github.com/bpavie/Colour_Deconvolution/blob/refactor/src/main/java/colourdeconvolution/MatrixTransformation.java
)
I will wait for more guidance before to implement another pull request
using an external text file to load the different matrix.

2015-11-19 16:34 GMT+01:00 Jan Eglinger notifications@github.com:

**Comment by landinig** [comment]
Maybe there is no need to update the vectors file ever. This will be local to each user/lab and they can share it in some other way if they wished so. 
As I said earlier, it is better NOT to rely on vectors determined by somebody else, but determine them yourself. It is perhaps not desirable to ship the CD plugin with too many vectors.
It could be that the plugin tries to open the vectors file, if it does not exist, create one, with a number of basic ones (RGB, CMY and some other) to which one can add more.

**Pull request closed without merging**
