### PR TITLE
Refactorized the code then moved all preset matrix into a text file, located in plugin

### PR DESCRIPTION
**Pull request by bpavie**
Refactorized the code so it could be also accessible from public method . Moved the matrix preset to an external text file. All the public methods are located in `StainMatrix` (see the comment/documentation in it)

### CODE REVIEW

**Comment by landinig** [comment]
Just a minor question and sorry I did not mention it before.
Would the text file be "readable/editable" in windows, linux and mac? I think that win editors tend to put LF/CR in all line breaks. So does the new code cope with the extra win characters if they exist?
Cheers
Gabriel

**Comment by bpavie** [comment]
@landinig Right now, since the rest of the code had Windows style end of line, I did the same for the text file. I am not sure we can format a text file so it is readable/editable in windows, linux and mac.
To read it, I use `readLine()` so it should work on both Unix/Windows, see the method `private LinkedHashMap<String,StainMatrix> getStainList() throws IOException` in `Colour_Deconvolution`. The only thing I am not sure of is where to store the text file and if/what I need to add something to the `pom.xml` file.

**Comment by landinig** [comment]
Perhaps in /plugins is the right place?
Can you drop me a private email please, I need to compile your modifications to test and I am not good at all with git.

**Comment by bpavie** [comment]
I am not sure where I can find your private email. But you can download the zipped project at [https://github.com/bpavie/Colour_Deconvolution/archive/externaltxt.zip](https://github.com/bpavie/Colour_Deconvolution/archive/externaltxt.zip).
[Here](https://github.com/bpavie/Colour_Deconvolution/tree/externaltxt) is the project with the corresponding branch (`externaltxt`)

**Comment by landinig** [comment]
My email/contact is in the source code and in my IJ plugins page, but thanks for the link to the source.
I will try to compile it with eclipse, which I have not used, (and being a package it does not compile from the Compile & Run command either).

**Comment by landinig** [comment]
I was successful in compiling this with Eclipse and it works fine, but if the plugin is merged  in this state, it will cause trouble for existing users.

I run it under IJ1 and found that: 
1) The colourdeconvolution.txt did not exist  in the /plugins folder. At the moment the file gets included in the jar file, but it is not visible to the plugin (so there were are no vectors available). I added it by hand and it seems to be OK. However, this will baffle users until (if) they find out what is going on.
If the file were made visible to the plugin from within the jar file, it would be difficult to edit it (need to unzip the jar file, edit the txt file, pack it again.
It would be also be difficult to maintain the vectors: the next time there is an update we lose the user-added vectors when the file is updated.

A practical solution would be for the plugin, at run time, to check the /plugins folder for this vector file. If it exists, it loads it, otherwise it creates a new one with the basic built-in default vectors.
That way you have same basic functionality, it would be a better way of adding new vectors and would prevent those to be replaced when there are updates.

2) Maybe there could be some more comments in the vector file, explaining that the file is comma delimited? For some reason the file had an unequal number of tabs on each line. Maybe this is due to some editor tab spacing or font size?

3) when reading the vectors file, I do not think it is necessary to output the result to the console.
Hope these comments are useful.

**Comment by ctrueden** [comment]
I think it is good to ship a default vectors file as a resource in the JAR. You just have to use `getClass().getResourceAsStream("colourdeconvolution.txt");` to read it, rather than looking for a file.

Making the vectors extensible is a separate issue, that I do not think should hold up this PR. It could be done by looking for an _additional_ vectors file on disk, as @landinig has suggested, and then merging it with the default vectors. Unless you think there is some compelling reason to support removal of built-in vectors, in which case I guess it could override it—though I like that less, for cases where the plugin itself ships an updated vectors list, which would then not be available to anyone who has customized the vectors previously.

**Comment by ctrueden** [comment]
Also, due to the package renames, this PR should bump the version in the `pom.xml` to the next major version: `3.0.0-SNAPSHOT`.

**Comment by ctrueden** [comment]
@bpavie I think at this point, @landinig and I await further updates from you. Unless anything is unclear?

**Comment by bpavie** [comment]
Thanks a lot for your feedback/advices. 
Jut to clarify, concerning the `colourdeconvolution.txt`, you would like to first test if the file is present in the plugin directory. If yes, I use this file and try to merge it with the one included in the Jar file (using `getClass().getResourceAsStream("colourdeconvolution.txt");`) ? Am I correct?
Do you have any suggestion on how to merge the 2 files? A naive way would be check the stain name. But what if the stain name is present in both file and the vector values are different. Which file should have the priority? The one in the jar file?

**Comment by landinig** [comment]
Hi I think it can and should be easier than that. No merge needed.

The plugin runs without any loading any vectors in the arrays,  and tries to open the text file. 
These are the options:
1)  It finds it, so it opens it to read all the vectors available in that file.
or
2)  It does not find it, so it creates one with a set of values (the ones currently in the txt file in the jar or in the code), and them reads it. There is no need to merge anything because the default values are written to the newly created file.

Therefore the "current vectors", should only be in the plugin source code to create the colourdeconvolution.txt file when it does not exist.
Thanks for looking into this.

**Comment by bpavie** [comment]
Otherwise, I was thinking to merge it so I read first the one inside the Jar, then if the file is present inside the plugin directory, I parse it. All the new stains are added, and the one already present are replaced by the value of the file in the plugin directory. Would it be OK like that ?

**Comment by landinig** [comment]
I think it is best to read all vectors from a single place that is fully editable.
That is why I am suggesting that if the file does not exist, write a number of 'default' vectors into that file, and if I want to change their values I also can.
If we start merging vectors with the same names from a file with those from inside the jar it will lead to confusion and it will also be tricky to know which one is which.
All from the singe files seems the easiest and safest option to me.

**Comment by bpavie** [comment]
So if the file is not present in the plugin directory, I copy the one from the jar file, then I read it.
Otherwise, I used the one in the plugin directory. Would it be OK like that?

**Comment by imagejan** [comment]
I like @bpavie 's suggestion to have both files, allow overriding the default values by the local file, but _avoid duplicating_ the default vectors into the local file: that allows updating the default vectors with changes that will actually be picked up (unless the user willingly overrides them by writing their own vectors with the same name).

**Comment by landinig** [comment]
@imagejan: no, sorry I would not think that is best. The default vectors are not updated often, you add to those. So far it has been only me who added them, (nobody has ever suggested new ones) so as a sample that is enough. If I add a new H&E which one is mine and which is the default? Unnecessarily complicated.

@bpavie: yes perfect, that is what I see as the best option: copy the file from the jar to /plugins, then read it.
Can I also suggest to have the txt without the tabs (which do not match across rows) and perhaps a simpler comment:
#Stain_Name, R0, G0, B0, R1, G1, B1, R2, G2, B2

Thanks

**Comment by bpavie** [comment]
That looks OK for me, except if the plugin directory is Read-only for some reason. If it is read-only, should I just put the writing part into a try catch so I can continue? And should I display an error popup?

**Comment by landinig** [comment]
Hm... I haven't considered that... 

Yes, in that case you could show a pop up message explaining and then read the local file (here we are again!)  so the user at least could try the plugin.

**Comment by imagejan** [comment]
> and then read the local file

There will be no local file if the folder is read-only (if we have the same understanding of "local file"; otherwise I should rephrase everything I said above...)

**Comment by landinig** [comment]
Ah, yes, it is a confusing term. 
I meant the file "inside the jar file" which then the plugin would copy into /plugins, if possible.

**Comment by landinig** [comment]
Right, I tested this and it seems to work well. Many thanks @bpavie for your contribution.
Any objections to merge?

**Comment by ctrueden** [comment]
LGTM :+1:

**Comment by landinig** [comment]
The plugin still outputs the vectors to the console at run time. I do not think this is necessary.
@bpavie if you get the time, can this be sorted, please?

**Pull request merged**
